### ISSUE TITLE
Mac m3 - Important Failed

### ISSUE THREAD

**Issue by Moltes74** [gokayfem/ComfyUI_VLM_nodes#103]
Hi,

I'm stuck with the installation, it keeps showing "important failure" even after unzipping the file and git pull...

Anyone here to help me ? 

Thanks !

**Comment by BenRacicot** [comment]
I think I'm seeing this demonstrated in another way.
The run script shows that it thinks my mac is 64 bit, but aside from that looks like an Apple Metal version was released this week and should probably be used instead.

[github.com/abetlen/llama-cpp-python/releases/tag/v0.3.1-metal](https://github.com/abetlen/llama-cpp-python/releases/tag/v0.3.1-metal)

This error is correct I think, the whl doesnt even seem to exist but I didn't look closely.

> Installing llama_cpp...
Error while checking AVX2 support: 'flags'
Python version: 311
OS: Darwin
OS bit: 64
Platform tag: cp311-cp311-macosx_15_0_arm64
Collecting llama-cpp-python==0.3.1
  ERROR: HTTP error 404 while getting https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.1/llama_cpp_python-0.3.1-cp311-cp311-macosx_15_0_arm64.whl
ERROR: Could not install requirement llama-cpp-python==0.3.1 from https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.1/llama_cpp_python-0.3.1-cp311-cp311-macosx_15_0_arm64.whl because of HTTP error 404 Client Error: Not Found for url: https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.1/llama_cpp_python-0.3.1-cp311-cp311-macosx_15_0_arm64.whl for URL https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.1/llama_cpp_python-0.3.1-cp311-cp311-macosx_15_0_arm64.whl

**Comment by bbaaxx** [comment]
@Moltes74 
You will need to provide more information about your specific environment such as your Python version and other dependencies. Without that information it will be hard to figure out what the problem may be.

I can confirm I have it running on a Mac M3 with very good performance, I installed it from the comfyui manager but I have other nodes that will install llama_cpp_python as well.
I am running python 3.12 and updated torch to the latest dev version.

I hope this helps
